# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.8.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
#label encoding of gender column 

In [7]:
print(X)
#here female was encoded into zero and male was encoded into 1

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
#we have to appply feature scaling for all the variables
#removing the selections of particular indices

## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()
#creates variable ann of object of sequential class

### Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
#shallow neural network

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
# neural network

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
#A weighted sum of inputs is passed through an activation function and this output serves as an input to the next layer. When the activation function for a neuron is a sigmoid function it is a guarantee that the output of this unit will always be between 0 and 1.
#unit is 1 because we need one neuron to encode the dependent variable

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam' ,loss= 'binary_crossentropy',metrics= ['accuracy'])
#compiling entire ann using an optimizer 

Training The ANN


In [18]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)
#fit method is always used to train 
#the classic value of batch size is taken as 32
#number of epochs-- 100

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.7421 - accuracy: 0.5186
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4979 - accuracy: 0.7951
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4470 - accuracy: 0.7974
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4232 - accuracy: 0.8136
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4069 - accuracy: 0.8259
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3911 - accuracy: 0.8374
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3776 - accuracy: 0.8451
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3680 - accuracy: 0.8490
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3615 - accuracy: 0.8501
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3576 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

Predicting test set results (for any input)


In [19]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
#final predicted output in binary form
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Predicting the Test set results

In [20]:
#we are making predictions to evaluate the model
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,600000,2,1,1,50000]])))
#we got the probablity

[[0.9995185]]


### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score
#scikit learn library already contains confusion metrics feature

cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)
#we got an accuracy of over 86 percent

[[1516   79]
 [ 194  211]]


0.8635